// Code generated by "stringer -type=RenderState"; DO NOT EDIT.

package bento

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hidden-0]
	_ = x[Entering-1]
	_ = x[Visible-2]
	_ = x[Exiting-3]
}

const _RenderState_name = "HiddenEnteringVisibleExiting"

var _RenderState_index = [...]uint8{0, 6, 14, 21, 28}

func (i RenderState) String() string {
	if i < 0 || i >= RenderState(len(_RenderState_index)-1) {
		return "RenderState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RenderState_name[_RenderState_index[i]:_RenderState_index[i+1]]
}
